### 회원가입기능
POST http://localhost:8080/member/sign-up
Content-Type: application/json

{
  "memberId": "황태원손님3",
  "password": "secretpassword",
  "phone": "123-456-7890",
  "memberType": "USER"
}

### 로그인기능, 로그인 성공 시 jwt를 발급합니다
POST http://localhost:8080/member/sign-in
Content-Type: application/json

{
  "memberId": "황태원손님",
  "password": "secretpassword"
}