###
POST http://localhost:8080/member/sign-up
Content-Type: application/json

{
  "memberId": "황태원찐점장",
  "password": "secretpassword",
  "phone": "123-456-7890",
  "memberType": "PARTNER"
}

###
POST http://localhost:8080/member/sign-in
Content-Type: application/json

{
  "memberId": "황태원찐점장",
  "password": "secretpassword"
}