### 해당 매장의 예약가능 시간을 가져옵니다.
GET http://localhost:8080/reservation/available-reservation-time?storeName=부천원종점
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmantg5zsm5DshpDri5giLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTY5MTM4NTgyNSwiZXhwIjoxNjkxMzg5NDI1fQ.0vVeuj8qFkWrUY03DsWPVX2vWgUGZIXstKtU6DygGyucF4oNfZEfipy2v9sy7CHxztuOIMjUIsNAilPkpyW08A

### 해당매장의 예약시간과 함께 예약을 요청합니다.
POST http://localhost:8080/reservation/request-reservation
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmantg5zsm5DshpDri5giLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTY5MTM4NTgyNSwiZXhwIjoxNjkxMzg5NDI1fQ.0vVeuj8qFkWrUY03DsWPVX2vWgUGZIXstKtU6DygGyucF4oNfZEfipy2v9sy7CHxztuOIMjUIsNAilPkpyW08A
Content-Type: application/json

{
  "storeName": "부천원종점",
  "reservationDate": "2023-08-09",
  "reservationTime": "10:00"
}

### 예약요청을 승인합니다.
POST http://localhost:8080/reservation/accept-reservation
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmantg5zsm5DsoJDsnqUiLCJyb2xlcyI6WyJQQVJUTkVSIl0sImlhdCI6MTY5MTM4NTg0OSwiZXhwIjoxNjkxMzg5NDQ5fQ.DjLZYkCswIsn6Abnujf5Obw1Z2UFovS_1RCZDbmZDlRGXQ6JJ9YRJ_eC8oD_C4xWsiJZSFEeqwpXJMhTu-INBQ
Content-Type: application/json

{
  "reservationId": "23080910100Y"
}

### 예약요청을 거부합니다. 취소사유가 함께 입력됩니다.
POST http://localhost:8080/reservation/cancel-reservation
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmantg5zsm5DsoJDsnqUiLCJyb2xlcyI6WyJQQVJUTkVSIl0sImlhdCI6MTY5MTM1MzQ1NSwiZXhwIjoxNjkxMzU3MDU1fQ.OFa9rQFDr5klRbNlOv13u9sbZH8RC9JHrFTh7YArjKxJgb_2enWqWI4v-qxQiZ1C01q7jM234jt_Vjpt_B-IKQ
Content-Type: application/json

{
  "reservationId": "23080609100JCY",
  "cancelDescription": "재료가 소진되었습니다."
}

### 매장을 도착하여 예약을 사용합니다.
POST http://localhost:8080/reservation/use-reservation
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmantg5zsm5DsoJDsnqUiLCJyb2xlcyI6WyJQQVJUTkVSIl0sImlhdCI6MTY5MTM4NTg0OSwiZXhwIjoxNjkxMzg5NDQ5fQ.DjLZYkCswIsn6Abnujf5Obw1Z2UFovS_1RCZDbmZDlRGXQ6JJ9YRJ_eC8oD_C4xWsiJZSFEeqwpXJMhTu-INBQ
Content-Type: application/json

{
  "reservationId": "23080910100Y"
}

### 나의 예약정보를 가져옵니다.
GET http://localhost:8080/reservation/get-reservation
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmantg5zsm5DshpDri5giLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTY5MTM2MTU1OSwiZXhwIjoxNjkxMzY1MTU5fQ.uCybnHb3ifAJ38KJMZ41-w1GdrXPC2W1XWA246eBkSxgVbyi6z3EPOkuB1D-rioSZ8L9soo2PF847zkMFrVjmw
