###
POST http://localhost:8080/store/register-store
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmantg5zsm5DsoJDsnqUiLCJyb2xlcyI6WyJQQVJUTkVSIl0sImlhdCI6MTY5MTI4NDY0OCwiZXhwIjoxNjkxMjg4MjQ4fQ.isBHcsM2oIccYZymdYuFsLlRJzgb1LsI8jFybGymy6GoTbZWovffoLX2mOVBewAMl6J2zZJ4MACzhgiUaDmDdQ
Content-Type: application/json

{
  "memberId": "황태원점장",
  "storeName": "부천원종점",
  "address": "삼작로 368번길 15-12",
  "storePhone": "010-4848-8253",
  "openTime": "09:00",
  "closeTime": "21:00"
}

###
GET http://localhost:8080/store/get-stores?page=0&size=5&sortingType=DISTANCE&lat=37.5189507&lnt=126.8033512
###
GET http://localhost:8080/store/get-stores?page=0&size=5&sortingType=NAME&lat=37.5189507&lnt=126.8033512
###
GET http://localhost:8080/store/get-stores?page=0&size=5&sortingType=RATING&lat=37.5189507&lnt=126.8033512
###
GET http://localhost:8080/store/get-store?storeName=부천원종점