###
POST http://localhost:8080/member/sign-up
Content-Type: application/json

{
  "memberName": "황태원점장",
  "password": "secretpassword",
  "phone": "123-456-7890",
  "memberType": "PARTNER"
}

###
POST http://localhost:8080/member/sign-in
Content-Type: application/json

{
  "memberName": "황태원점장",
  "password": "secretpassword"
}

###
GET http://localhost:8080/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiLtmantg5zsm5DsoJDsnqUiLCJyb2xlcyI6WyJQQVJUTkVSIl0sImlhdCI6MTY5MDc0NDA1MCwiZXhwIjoxNjkwNzQ3NjUwfQ.CsH1SZ7IxDpv20xL2Tc-bRjlSEYplWvvjz0MegoOH3RCi2o5k9XYKgqpvd-ZvpGBMvvzWiJVhuysYmOyqu2Czg